import { randomUUID } from "node:crypto";
import { ZoteroCitationItem, ZoteroCslCitation } from "../types/csl-types.js";
import { escapeXml } from "./xml-utils.js";

export function generateZoteroFieldCode(
  citationItems: ZoteroCitationItem[],
  formattedText: string
): string {
  const citationId = randomUUID().slice(0, 8);

  const cslCitation: ZoteroCslCitation = {
    citationID: citationId,
    properties: { formattedCitation: formattedText },
    citationItems,
    schema:
      "https://github.com/citation-style-language/schema/raw/master/csl-citation.json",
  };

  const instrText = ` ADDIN ZOTERO_ITEM CSL_CITATION ${JSON.stringify(cslCitation)} `;
  const escapedInstrText = escapeXml(instrText);

  return [
    '<w:r><w:fldChar w:fldCharType="begin"/></w:r>',
    `<w:r><w:instrText xml:space="preserve">${escapedInstrText}</w:instrText></w:r>`,
    '<w:r><w:fldChar w:fldCharType="separate"/></w:r>',
    `<w:r><w:rPr><w:noProof/></w:rPr><w:t>${escapeXml(formattedText)}</w:t></w:r>`,
    '<w:r><w:fldChar w:fldCharType="end"/></w:r>',
  ].join("");
}

export function generateBibliographyFieldCode(): string {
  return [
    "<w:p>",
    '<w:r><w:fldChar w:fldCharType="begin"/></w:r>',
    '<w:r><w:instrText xml:space="preserve">',
    " ADDIN ZOTERO_BIBL {&quot;uncited&quot;:[],&quot;omitted&quot;:[],&quot;custom&quot;:[]} CSL_BIBLIOGRAPHY ",
    "</w:instrText></w:r>",
    '<w:r><w:fldChar w:fldCharType="separate"/></w:r>',
    "<w:r><w:rPr><w:noProof/></w:rPr><w:t>[Bibliography will be generated by Zotero]</w:t></w:r>",
    '<w:r><w:fldChar w:fldCharType="end"/></w:r>',
    "</w:p>",
  ].join("");
}
