import { describe, it, expect } from "vitest";
import { generateZoteroFieldCode, generateBibliographyFieldCode } from "./field-codes.js";
import { ZoteroCitationItem } from "../types/csl-types.js";

describe("generateZoteroFieldCode", () => {
  const citationItem: ZoteroCitationItem = {
    id: 0,
    uris: ["http://zotero.org/users/12345/items/ABC001"],
    uri: ["http://zotero.org/users/12345/items/ABC001"],
    itemData: {
      type: "article-journal",
      title: "Test Paper",
      author: [{ family: "Smith", given: "John" }],
      issued: { "date-parts": [["2023"]] },
    },
  };

  it("generates XML with begin field char", () => {
    const xml = generateZoteroFieldCode([citationItem], "(Smith, 2023)");
    expect(xml).toContain('w:fldCharType="begin"');
  });

  it("generates XML with instrText containing ADDIN ZOTERO_ITEM", () => {
    const xml = generateZoteroFieldCode([citationItem], "(Smith, 2023)");
    expect(xml).toContain("ADDIN ZOTERO_ITEM CSL_CITATION");
  });

  it("generates XML with escaped JSON in instrText", () => {
    const xml = generateZoteroFieldCode([citationItem], "(Smith, 2023)");
    expect(xml).toContain("&quot;citationID&quot;");
    expect(xml).toContain("&quot;citationItems&quot;");
  });

  it("generates XML with separate field char", () => {
    const xml = generateZoteroFieldCode([citationItem], "(Smith, 2023)");
    expect(xml).toContain('w:fldCharType="separate"');
  });

  it("generates XML with visible text", () => {
    const xml = generateZoteroFieldCode([citationItem], "(Smith, 2023)");
    expect(xml).toContain("<w:t>(Smith, 2023)</w:t>");
  });

  it("generates XML with end field char", () => {
    const xml = generateZoteroFieldCode([citationItem], "(Smith, 2023)");
    expect(xml).toContain('w:fldCharType="end"');
  });

  it("generates XML with noProof on visible text", () => {
    const xml = generateZoteroFieldCode([citationItem], "(Smith, 2023)");
    expect(xml).toContain("<w:noProof/>");
  });
});

describe("generateBibliographyFieldCode", () => {
  it("generates paragraph with ZOTERO_BIBL", () => {
    const xml = generateBibliographyFieldCode();
    expect(xml).toContain("ADDIN ZOTERO_BIBL");
  });

  it("generates begin/separate/end structure", () => {
    const xml = generateBibliographyFieldCode();
    expect(xml).toContain('w:fldCharType="begin"');
    expect(xml).toContain('w:fldCharType="separate"');
    expect(xml).toContain('w:fldCharType="end"');
  });

  it("wraps in a paragraph", () => {
    const xml = generateBibliographyFieldCode();
    expect(xml).toMatch(/^<w:p>.*<\/w:p>$/);
  });

  it("contains CSL_BIBLIOGRAPHY", () => {
    const xml = generateBibliographyFieldCode();
    expect(xml).toContain("CSL_BIBLIOGRAPHY");
  });

  it("contains placeholder text for bibliography", () => {
    const xml = generateBibliographyFieldCode();
    expect(xml).toContain("[Bibliography will be generated by Zotero]");
  });
});
